<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-HLE2G3S" name="Invest" tests="16" failures="1" timestamp="23 Mar 2019 13:33:33 GMT" time="1.05" errors="0">
  <testcase name="f2" time="0.004" classname="com.testng.Invest_Forward_Test"/>
  <testcase name="f1" time="0.001" classname="com.testng.Invest_Forward_Test"/>
  <testcase name="f3" time="0.001" classname="com.testng.Invest_Reverse_Test"/>
  <testcase name="f4" time="0.001" classname="com.testng.Invest_Reverse_Test"/>
  <testcase name="f3" time="0.0" classname="com.testng.NoNormalMethod"/>
  <testcase name="f4" time="1.006" classname="com.testng.NoNormalMethod"/>
  <testcase name="f5" time="0.001" classname="com.testng.NoNormalMethod"/>
  <testcase name="f7" time="0.0" classname="com.testng.NoNormalMethod"/>
  <testcase name="f6" time="0.0" classname="com.testng.NoNormalMethod"/>
  <testcase name="f1" time="0.0" classname="com.testng.NoNormalMethod"/>
  <testcase name="test_case" time="0.002" classname="com.testng.DataProviderTest"/>
  <testcase name="test_case" time="0.0" classname="com.testng.DataProviderTest"/>
  <testcase name="test_case" time="0.001" classname="com.testng.DataProviderTest"/>
  <testcase name="test_case" time="0.001" classname="com.testng.DataProviderTest"/>
  <testcase name="test_case" time="0.0" classname="com.testng.DataProviderTest"/>
  <testcase name="test_case" time="0.001" classname="com.testng.DataProviderTest">
    <failure type="java.lang.AssertionError" message="expected [1202.0] but found [1201.0]">
      <![CDATA[java.lang.AssertionError: expected [1202.0] but found [1201.0]
	at com.testng.DataProviderTest.test_case(DataProviderTest.java:25)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test_case -->
</testsuite> <!-- Invest -->
